name: CI Pipeline

on:
  push:
    branches: [ "main", "frontend-dev", "backend-dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js for Backend
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Backend Dependencies
      run: npm install
      working-directory: ./backend

    - name: Set up Node.js for Frontend
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Frontend Dependencies
      run: npm install
      working-directory: ./frontend

    - name: Build Frontend
      run: npm run build
      working-directory: ./frontend

    - name: Test Docker Compose Build
      run: docker-compose build
